# RUSSI SINHA
# A20411286
# CS 512 - Computer Vision
# Fall 2018

In [1]:
import numpy as np

A = np.array([[1,2,3]]).T
B = np.array([[4,5,6]]).T
C = np.array([[-1,1,3]]).T
print '2*A-B = ', 2*A-B

2*A-B =  [[-2]
 [-1]
 [ 0]]


In [2]:
import math

norm_A = np.linalg.norm(A)
print '||A|| = ', norm_A
angle_A = math.degrees(np.arccos(1/norm_A))
print 'angle of A = ', angle_A

||A|| =  3.7416573867739413
angle of A =  74.4986404331


In [3]:
A_cap = A/norm_A
print 'A_cap = ', A_cap

A_cap =  [[0.26726124]
 [0.53452248]
 [0.80178373]]


In [4]:
alpha = A[0][0]/norm_A
print 'cosine_alpha = ', alpha

beta = A[1][0]/norm_A
print 'cosine_beta = ', beta

gamma = A[2][0]/norm_A
print 'cosine_gamma = ', gamma

cosine_alpha =  0.2672612419124244
cosine_beta =  0.5345224838248488
cosine_gamma =  0.8017837257372732


In [5]:
AdotB = np.dot(A.T,B)
print 'A.B = ', AdotB

BdotA = np.dot(B.T,A)
print 'B.A = ', BdotA


A.B =  [[32]]
B.A =  [[32]]


In [6]:
norm_B = np.linalg.norm(B)

angle_AB = math.degrees(np.arccos(AdotB/(norm_A*norm_B)))
print 'Angle between A and B = ', angle_AB

Angle between A and B =  12.9331544919


In [7]:
X = np.array([[1,1,-1]]).T
print 'Assuming X = ', X
AdotX = np.dot(A.T, X)

angle_AX = math.degrees(np.arccos(AdotX))
print 'Angle between A and X = ', angle_AX
print 'Therefore, vector X is perpendicular to A'

Assuming X =  [[ 1]
 [ 1]
 [-1]]
Angle between A and X =  90.0
Therefore, vector X is perpendicular to A


In [8]:
AcrossB = np.cross(A.T,B.T)
print 'A X B = ', AcrossB

BcrossA = np.cross(B.T,A.T)
print 'B X A = ', BcrossA

A X B =  [[-3  6 -3]]
B X A =  [[ 3 -6  3]]


In [9]:
print 'A vector which is perpendicular to both A and B is A X B which is \n', AcrossB

A vector which is perpendicular to both A and B is A X B which is 
[[-3  6 -3]]


In [10]:
print 'A(transpose)B = ', np.dot(A.T,B)

print 'AB(transpose) = ', np.dot(A,B.T)

A(transpose)B =  [[32]]
AB(transpose) =  [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [11]:
A1 = np.matrix([[1,2,3],[4,-2,3],[0,5,-1]])
B1 = np.matrix([[1,2,1],[2,1,-4],[3,-2,1]])
C1 = np.matrix([[1,2,3],[4,5,6],[-1,1,3]])

print '2A-B = ',2*A1-B1

2A-B =  [[ 1  2  5]
 [ 6 -5 10]
 [-3 12 -3]]


In [12]:
print 'AB = ', np.dot(A1,B1)
print 'BA = ', np.dot(B1,A1)

AB =  [[ 14  -2  -4]
 [  9   0  15]
 [  7   7 -21]]
BA =  [[  9   3   8]
 [  6 -18  13]
 [ -5  15   2]]


In [13]:
print '(AB)transpose = ', (np.dot(A1,B1)).T

print 'B(transpose)A(transpose) = ', np.dot(B1.T,A1.T)

(AB)transpose =  [[ 14   9   7]
 [ -2   0   7]
 [ -4  15 -21]]
B(transpose)A(transpose) =  [[ 14   9   7]
 [ -2   0   7]
 [ -4  15 -21]]


In [14]:
det_A = np.linalg.det(A1)
print '|A| = ', det_A

det_C = np.linalg.det(C1)
print '|C| = ', det_C

|A| =  54.999999999999964
|C| =  7.494005416219837e-16


In [15]:
A_AT = np.dot(A1,A1.T)
print(A_AT)

B_BT = np.dot(B1,B1.T)
print(B_BT)

C_CT = np.dot(C1,C1.T)
print(C_CT)

print 'B forms an orthogonal set'

[[ 14   9   7]
 [  9  29 -13]
 [  7 -13  26]]
[[ 6  0  0]
 [ 0 21  0]
 [ 0  0 14]]
[[14 32 10]
 [32 77 19]
 [10 19 11]]
B forms an orthogonal set


In [16]:
A_inverse = np.linalg.inv(A1)
print 'Inverse of A = ', A_inverse

B_inverse = np.linalg.inv(B1)
print 'Inverse of B = ', B_inverse

Inverse of A =  [[-0.23636364  0.30909091  0.21818182]
 [ 0.07272727 -0.01818182  0.16363636]
 [ 0.36363636 -0.09090909 -0.18181818]]
Inverse of B =  [[ 0.16666667  0.0952381   0.21428571]
 [ 0.33333333  0.04761905 -0.14285714]
 [ 0.16666667 -0.19047619  0.07142857]]


In [17]:
A2 = np.array([[1,2],[3,2]])
B2 = np.array([[2,-2],[-2,5]])

A_eig = np.linalg.eig(A2)
A_eigvalues = A_eig[0]
print 'Eigenvalues of A = ', A_eigvalues

A_eigvectors = A_eig[1]
print 'Eigenvectors of A = ', A_eigvectors

Eigenvalues of A =  [-1.  4.]
Eigenvectors of A =  [[-0.70710678 -0.5547002 ]
 [ 0.70710678 -0.83205029]]


In [18]:
print '(V-inverse)(AV) = ', np.dot(np.linalg.inv(A_eigvectors), np.dot(A2, A_eigvectors))

(V-inverse)(AV) =  [[-1.00000000e+00 -6.66133815e-16]
 [ 0.00000000e+00  4.00000000e+00]]


In [19]:
A_eigvectors_dot = np.dot(A_eigvectors[0], A_eigvectors[1])
print 'Dot product of A_eigvectors = ', A_eigvectors_dot

Dot product of A_eigvectors =  -0.038461538461538214


In [20]:
B_eig = np.linalg.eig(B2)
B_eigvectors = B_eig[1]

B_eigvectors_dot = np.dot(B_eigvectors[0], B_eigvectors[1])
print 'Dot product of B_eigvectors = ', B_eigvectors_dot

Dot product of B_eigvectors =  0.0
